### ISSUE TITLE
"add a control" Error message to try edit with elementor an ele template plugin activated

### ISSUE THREAD

**Issue by cesardh** [dudaster/eletheme#20] opened 2018-07-18 05:25 UTC
I have this message:
> ElementorPro\Modules\Posts\Widgets\Posts::add_control: Cannot add a control outside of a section (use `start_controls_section`).

when I go to edit something whit elementor, and Elementor works fine before I desactivate Ele Themplate plugin.

**Comment by dudaster** [comment] 2018-07-19 08:30
I assume saying "Ele Themplate plugin" you are referring to Eletheme theme.
I can't reproduce this.
Let me know if there is a conflict with other plugins that you have installed (except elementor ofcourse).

**Comment by dudaster** [comment] 2018-08-09 07:20
Almost a month passed. I'll close it for the time being.

**Closed as completed by dudaster** 2018-08-09 07:20 UTC

**Comment by 00Cedge** [comment] 2018-09-27 16:41
Hi Dudaster,  
I have the same error: **ElementorPro\Modules\ThemeBuilder\Widgets\Archive_Posts::add_control: Cannot add a control outside of a section (use `start_controls_section`).**

The plugin was working fine initially.  I created a loop template fine then tried to make an Archive post (not sure what I'm doing to be honest.  I'm trying to make a searchable CPT Archive with a custom video skin ).  
I think when I added another Display condition to a CPT that already had a display condition from another template may have caused the error.
I can't replicate it now though because if the plugin is activated that error will display on all elementor pages.

Many thanks
